name: ilhayoung_app
description: "제주 일자리 플랫폼 - 일하영"
publish_to: 'none'

version: 888.0.1+30

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # 기존 패키지들
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1

  # 카카오 로그인 SDK
  kakao_flutter_sdk: ^1.9.1

  # OAuth 로그인용 패키지들
  url_launcher: ^6.2.1             # URL 실행
  webview_flutter: ^4.4.2          # WebView OAuth 로그인
  shared_preferences: ^2.2.2       # 토큰 저장용
  http: ^1.1.0                      # API 통신용

  # 추가 유틸리티 패키지들
  intl: ^0.19.0                     # 날짜/시간 포맷팅
  table_calendar: ^3.0.9            # 달력 위젯

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true

  # Assets 설정 (주석 해제)
  assets:
    - assets/images/

flutter_native_splash:
  # 기본 설정만
  color: "#F8FFFE"  # 배경색
  image: assets/images/splash_logo.png  # 로고만

  # 안드로이드 12+ 기본 설정
  android_12:
    color: "#F8FFFE"
    icon_background_color: "#00A3A3"

  # 플랫폼 설정
  android: true
  ios: true